// Generated by CoffeeScript 1.6.3
var SassCompiler, exec, progeny, spawn, sysPath, _ref;

_ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

sysPath = require('path');

progeny = require('progeny');

module.exports = SassCompiler = (function() {
  SassCompiler.prototype.brunchPlugin = true;

  SassCompiler.prototype.type = 'stylesheet';

  SassCompiler.prototype.extension = 'scss';

  SassCompiler.prototype.pattern = /\.s[ac]ss$/;

  SassCompiler.prototype._bin = process.platform === 'win32' ? 'sass.bat' : 'sass';

  SassCompiler.prototype._compass_bin = 'compass';

  function SassCompiler(config) {
    var bin_cmd, compass_bin_cmd, env, k, v, _ref1, _ref2, _ref3, _ref4,
      _this = this;
    this.config = config;
    this.gem_home = (_ref1 = this.config.plugins) != null ? (_ref2 = _ref1.sass) != null ? _ref2.gem_home : void 0 : void 0;
    this.mod_env = {};
    if (this.gem_home) {
      env = ((function() {
        var _ref3, _results;
        _ref3 = process.env;
        _results = [];
        for (k in _ref3) {
          v = _ref3[k];
          _results.push([k, v]);
        }
        return _results;
      })()).reduce(function(a, _arg) {
        var k, v;
        if (a == null) {
          a = {};
        }
        k = _arg[0], v = _arg[1];
        a[k] = v;
        return a;
      });
      env['GEM_HOME'] = config.plugins.sass.gem_home;
      this.mod_env = {
        env: env
      };
      this._bin = this.config.plugins.sass.gem_home + '/bin/sass';
      this._compass_bin = this.config.plugins.sass.gem_home + '/bin/compass';
    }
    if ((_ref3 = this.config.plugins) != null ? (_ref4 = _ref3.sass) != null ? _ref4.useBundler : void 0 : void 0) {
      bin_cmd = "bundle exec " + this._bin;
      compass_bin_cmd = "bundle exec " + this._compass_bin;
    } else {
      bin_cmd = this._bin;
      compass_bin_cmd = this._compass_bin;
    }
    exec("" + bin_cmd + " --version", this.mod_env, function(error, stdout, stderr) {
      if (error) {
        console.error("You need to have Sass on your system");
        return console.error("Execute `gem install sass`");
      }
    });
    exec("" + compass_bin_cmd + " --version", this.mod_env, function(error, stdout, stderr) {
      return _this.compass = !error;
    });
    this.getDependencies = progeny({
      rootPath: this.config.paths.root
    });
  }

  SassCompiler.prototype.compile = function(data, path, callback) {
    var delay, error, execute, hasComments, options, result, _ref1, _ref2, _ref3, _ref4,
      _this = this;
    result = '';
    error = null;
    options = ['--stdin', '--load-path', this.config.paths.root, '--load-path', sysPath.dirname(path), '--no-cache'];
    if (!this.config.optimize) {
      hasComments = ((_ref1 = this.config.plugins) != null ? (_ref2 = _ref1.sass) != null ? _ref2.debug : void 0 : void 0) === 'comments';
      options.push((hasComments ? '--line-comments' : '--debug-info'));
    }
    if (((_ref3 = this.config.plugins) != null ? (_ref4 = _ref3.sass) != null ? _ref4.options : void 0 : void 0) != null) {
      options.push.apply(options, this.config.plugins.sass.options);
    }
    if (/\.scss$/.test(path)) {
      options.push('--scss');
    }
    execute = function() {
      var bin, onExit, sass, _ref5, _ref6;
      if (_this.compass) {
        options.push('--compass');
      }
      if ((_ref5 = _this.config.plugins) != null ? (_ref6 = _ref5.sass) != null ? _ref6.useBundler : void 0 : void 0) {
        bin = 'bundle';
        options.unshift('exec', 'sass');
      } else {
        bin = _this._bin;
      }
      sass = spawn(bin, options, _this.mod_env);
      sass.stdout.on('data', function(buffer) {
        return result += buffer.toString();
      });
      sass.stderr.on('data', function(buffer) {
        if (error == null) {
          error = '';
        }
        return error += buffer.toString();
      });
      onExit = function(code) {
        return callback(error, result);
      };
      if (process.version.slice(0, 4) === 'v0.6') {
        sass.on('exit', onExit);
      } else {
        sass.on('close', onExit);
      }
      if (sass.stdin.write(data)) {
        return sass.stdin.end();
      } else {
        return sass.stdin.on('drain', function() {
          return sass.stdin.end();
        });
      }
    };
    delay = function() {
      if (_this.compass != null) {
        return execute();
      } else {
        return setTimeout(delay, 100);
      }
    };
    return delay();
  };

  return SassCompiler;

})();
